dist: xenial
language: python
cache: pip
git:
  depth: 1

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

env:
  - DJANGO=1.11
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master

matrix:
  include:
    - env: TOXENV=flake8
      python: 3.8
    - env: TOXENV=isort
      python: 3.8
    - env: TOXENV=black
      python: 3.8
  exclude:
    - env: DJANGO=1.11
      python: 3.8
    - env: DJANGO=2.0
      python: 3.8
    - env: DJANGO=2.1
      python: 3.8
    - env: DJANGO=3.0
      python: 3.5
    - env: DJANGO=master
      python: 3.5
    - env: DJANGO=master
      python: 3.6
    - env: DJANGO=master
      python: pypy3
  allow_failures:
    - env:
      - DJANGO=master
    - env:
      - TOXENV=isort
    - env:
      - TOXENV=black

install: pip install tox-travis

script: tox
